export const shipNames = [
    "lightFighter",
    "heavyFighter",
    "cruiser",
    "battleship",
    "battlecruiser",
    "bomber",
    "destroyer",
    "reaper",
    "pathfinder",
    "smallCargo",
    "largeCargo",
    "colonyShip",
    "recycler",
    "espionageProbe",
    "solarSatellite",
    "crawler",
] as const
